version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres-image
    build: ./database/
    networks:
      - skynet
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - pg_data:${PGDATA}
  node:
    container_name: node
    image: app-image
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - skynet
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/app/src
      - logs:/usr/app
networks:
  skynet:
    driver: bridge
volumes:
  logs:
  pg_data:
