version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres-image
    build: ./database/
    networks:
      - skynet
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: ./.env
    volumes:
      - pg_data:${PGDATA}
  node:
    container_name: node
    image: app-image
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - skynet
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/app/src
      - app_logs:/usr/app
networks:
  skynet:
    driver: bridge
volumes:
  app_logs:
  pg_data:
